#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class SharedStruct
  include ::Thrift::Struct, ::Thrift::Struct_Union
  KEY = 1
  VALUE = 2

  FIELDS = {
    KEY => {:type => ::Thrift::Types::I32, :name => 'key'},
    VALUE => {:type => ::Thrift::Types::STRING, :name => 'value'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

